services:
  - type: web
    name: qa-packet-validator
    env: docker
    plan: free
    autoDeploy: true
    build:
      commands:
        - RUN apt-get update && apt-get install -y tesseract-ocr && rm -rf /var/lib/apt/lists/*